!function(){

	module.exports : {
		fn: {
			  ABS 								: true
			, ACOS 								: true
			, ADDDATE 							: true
			, ADDTIME 							: true
			, AES_DECRYPT 						: true
			, AESAES_ENCRYPT 					: true
			, ANDASCII 							: true
			, ASIN 								: true
			, ATAN2 							: true
			, ATAN 								: true
			, ATAN 								: true
			, AVG 								: true
			, BENCHMARK 						: true
			, BIN 								: true
			, BIT_AND 							: true
			, BIT_COUNT 						: true
			, BIT_LENGTH 						: true
			, BIT_OR 							: true
			, BIT_XOR 							: true
			, CAST 								: true
			, CEIL 								: true
			, CEILING 							: true
			, CHAR_LENGTH 						: true
			, CHAR 								: true
			, CHARACTER_LENGTH 					: true
			, CHAR_LENGTH 						: true
			, CHARSET 							: true
			, COALESCE 							: true
			, COERCIBILITY 						: true
			, COLLATION 						: true
			, COMPRESS 							: true
			, CONCAT_WS 						: true
			, CONCAT 							: true
			, CONNECTION_ID 					: true
			, CONV 								: true
			, CONVERT_TZ 						: true
			, CONVERT 							: true
			, COS 								: true
			, COT 								: true
			, COUNT 							: true
			, CRC32 							: true
			, CURDATE 							: true
			, CURRENT_DATE 						: true
			, CURDATE 							: true
			, CURRENT_TIME 						: true
			, CURTIME 							: true
			, CURRENT_TIMESTAMP 				: true
			, NOW 								: true
			, CURRENT_USER 						: true
			, CURTIME 							: true
			, DATABASE 							: true
			, DATE_ADD 							: true
			, DATE_FORMAT 						: true
			, DATE_SUB 							: true
			, DATE 								: true
			, DATEDIFF 							: true
			, DAY 								: true
			, DAYOFMONTH 						: true
			, DAYNAME 							: true
			, DAYOFMONTH 						: true
			, DAYOFWEEK 						: true
			, DAYOFYEAR 						: true
			, DECODE 							: true
			, ENCODE 							: true
			, DEFAULT 							: true
			, DEGREES 							: true
			, DES_DECRYPT 						: true
			, DES_ENCRYPT 						: true
			, ELT 								: true
			, ENCODE 							: true
			, ENCRYPT 							: true
			, EXP 								: true
			, EXPORT_SET 						: true
			, EXTRACT 							: true
			, FIELD 							: true
			, FIND_IN_SET 						: true
			, FLOOR 							: true
			, FORMAT 							: true
			, FOUND_ROWS 						: true
			, FROM_BASE64 						: true
			, FROM_DAYS 						: true
			, FROM_UNIXTIME 					: true
			, GET_FORMAT 						: true
			, GET_LOCK 							: true
			, GREATEST 							: true
			, GROUP_CONCAT 						: true
			, GTID_SUBSET 						: true
			, GTID_SUBTRACT 					: true
			, HEX 								: true
			, HOUR 								: true
			, IF 								: true
			, IFNULL 							: true
			, IN 								: true
			, INET_ATON 						: true
			, INET_NTOA 						: true
			, INET6_ATON 						: true
			, INET6_NTOA 						: true
			, INSERT 							: true
			, INSTR 							: true
			, INTERVAL 							: true
			, IS_FREE_LOCK 						: true
			, IS_IPV4_COMPAT 					: true
			, IS_IPV4_MAPPED 					: true
			, IS_IPV4 							: true
			, IS_IPV6 							: true
			, IS_USED_LOCK 						: true
			, ISNULL 							: true
			, LAST_INSERT_ID 					: true
			, INSERTLCASE 						: true
			, LOWER 							: true
			, LEAST 							: true
			, LEFT 								: true
			, LENGTH 							: true
			, LN 								: true
			, LOAD_FILE 						: true
			, LOCALTIME 						: true
			, NOW 								: true
			, LOCALTIMESTAMP 					: true
			, NOW 								: true
			, LOCATE 							: true
			, LOG10 							: true
			, LOG2 								: true
			, LOG 								: true
			, LOWER 							: true
			, LPAD 								: true
			, LTRIM 							: true
			, MAKE_SET 							: true
			, MAKEDATE 							: true
			, MAKETIME 							: true
			, MASTER_POS_WAIT 					: true
			, MAX 								: true
			, MD5 								: true
			, MICROSECOND 						: true
			, MID 								: true
			, MIN 								: true
			, MINUTE 							: true
			, MOD 								: true
			, MONTH 							: true
			, MONTHNAME 						: true
			, NAME_CONST 						: true
			, IN 								: true
			, NOW 								: true
			, NULLIF 							: true
			, 2OCT 								: true
			, OCTET_LENGTH 						: true
			, LENGTH 							: true
			, OLD_PASSWORD 						: true
			, ORORD 							: true
			, PASSWORD 							: true
			, PERIOD_ADD 						: true
			, PERIOD_DIFF 						: true
			, PI 								: true
			, POSITION 							: true
			, LOCATE 							: true
			, POW 								: true
			, POWER 							: true
			, ANALYSE 							: true
			, QUARTER 							: true
			, QUOTE 							: true
			, RADIANS 							: true
			, RAND 								: true
			, RELEASE_LOCK 						: true
			, REPEAT 							: true
			, REPLACE 							: true
			, REVERSE 							: true
			, RIGHT 							: true
			, REGEXPROUND 						: true
			, ROW_COUNT 						: true
			, RPAD 								: true
			, RTRIM 							: true
			, SCHEMA 							: true
			, DATABASE 							: true
			, SEC_TO_TIME 						: true
			, SECOND 							: true
			, SESSION_USER 						: true
			, USER 								: true
			, SHA1 								: true
			, SHA 								: true
			, SHA2 								: true
			, SIGN 								: true
			, SIN 								: true
			, SLEEP 							: true
			, SOUNDEX 							: true
			, SPACE 							: true
			, SQRT 								: true
			, STD 								: true
			, STDDEV_POP 						: true
			, STDDEV_SAMP 						: true
			, STDDEV 							: true
			, STR_TO_DATE 						: true
			, STRCMP 							: true
			, SUBDATE 							: true
			, DATE_SUB 							: true
			, SUBSTR 							: true
			, SUBSTRING_INDEX 					: true
			, SUBSTRING 						: true
			, SUBTIME 							: true
			, SUM 								: true
			, SYSDATE 							: true
			, SYSTEM_USER 						: true
			, USER 								: true
			, TAN 								: true
			, TIME_FORMAT 						: true
			, TIME_TO_SEC 						: true
			, TIME 								: true
			, TIMEDIFF 							: true
			, TIMESTAMP 						: true
			, TIMESTAMPADD 						: true
			, TIMESTAMPDIFF 					: true
			, TO_BASE64 						: true
			, TO_DAYS 							: true
			, TO_SECONDS 						: true
			, TRIM 								: true
			, TRUNCATE 							: true
			, UCASE 							: true
			, UPPER 							: true
			, UNCOMPRESS 						: true
			, UNCOMPRESSED_LENGTH 				: true
			, UNHEX 							: true
			, UNIX_TIMESTAMP 					: true
			, XML 								: true
			, UPPER 							: true
			, USER 								: true
			, UTC_DATE 							: true
			, UTC_TIME 							: true
			, UTC_TIMESTAMP 					: true
			, UUID_SHORT 						: true
			, UUID 								: true
			, VALIDATE_PASSWORD_STRENGTH 		: true
			, VALUES 							: true
			, INSERTVAR_POP 					: true
			, VAR_SAMP 							: true
			, VARIANCE 							: true
			, VERSION 							: true
			, WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS : true
			, WEEK 								: true
			, WEEKDAY 							: true
			, WEEKOFYEAR 						: true
			, WEIGHT_STRING 					: true
			, XOR 								: true
			, EAR 								: true
			, YEARWEEK 							: true
		}
	}
}();